In [1]:
#!pip install numpy

You should consider upgrading via the '/Users/apal/.pyenv/versions/3.8.8/bin/python3.8 -m pip install --upgrade pip' command.


***
# NUMPY
***
<font color = #318CE7 size = 3 >

> **What is NUMPY ?**

__NumPy (short for `Num`erical `Py`thon) is an open source Python library for doing scientific computing with Python.__

***

> `NumPy is the foundation of the python scientific stack`


<font>

[NUMPY REFERENCE](http://scipy-lectures.org/intro/numpy/index.html)

***

## Import 

In [8]:
import numpy as np
import random

## Compare Python List vs Numpy array

In [29]:
x_list = [i*random.randint(0,9) for i in range(100000)]

In [30]:
%%time
x_list.sort()

CPU times: user 25.1 ms, sys: 1.24 ms, total: 26.4 ms
Wall time: 26.3 ms


In [31]:
x_np_array = np.array(x_list)

In [32]:
%%time
x_np_array.sort()

CPU times: user 3.17 ms, sys: 1.51 ms, total: 4.68 ms
Wall time: 2 ms


## Array creation

In [34]:
#Converting Python sequences to NumPy Arrays

a = [1,2,3,4,5,6,7,8,9]
print(type(a))
np_a = np.array(a)
print(type(np_a))

<class 'list'>
<class 'numpy.ndarray'>


In [ ]:
# 1d-array
import numpy as np

my_list = [10.1,   2 , 1]
array1d = np.array(my_list)
array1d

In [ ]:
my_sublist = [
    [1.5, 2.5, 3.5, 4],
    [4.5, 5.5, 6.5, 1],
    [7.5, 8.5, 9.5, 6]
] # list of three by four list
my_sublist

In [ ]:
# if I cast the above list into an array : i get output as a 2d-array
array2d = np.array(my_sublist)
array2d

In [ ]:
array3d = np.array([
    
    [['R', 'G', 'B'], ['R', 'G', 'B']], 
    
    
    [['R', 'G', 'B'], ['R', 'G', 'B']]
])
array3d


### - **` Some Default Attributes `**
***
<font color = #318CE7 size = 3 >
    
> **The main data structure for multidimensional arrays in NumPy is the `ndarray class`.**

Attribute    :    Description <BR>

- `shape` : specifies the number of elements for each dimension of the array.
- `size` : total number elements in the array.
- `ndim` : Determines the dimension an array.
- `nbytes` : Number of bytes used to store the data.  
- `dtype` : Determines the datatype of elements stored in array.
    
***

</font>

***

In [5]:
print(array1d.shape) 
print(array2d.shape) 
# print(array3d.shape)

(3,)
(3, 4)


In [6]:
print(array1d.ndim)
print(array2d.ndim)
# print(array3d.ndim)

1
2



### - **` Reshape an array `**
***
<font color = #318CE7 size = 3 >
    
 > The `reshape()` method modifies existing shape but original array remains unchanged.
 
</font>

***

In [36]:
np_a.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
thearray = np.array([1, 2, 3, 4, 5, 6, 7, 8])
thearray = thearray.reshape(2, 4)
print(thearray)
 
print("-" * 20)

thearray = thearray.reshape(4, 2)
print(thearray)
 
print("-" * 20)

thearray = thearray.reshape(8, 1)
print(thearray)


### - **` Resize an array `**
***
<font color = #318CE7 size = 3 >
    
 > The `resize()` method modifies existing shape and array itself.
 
</font>

***

In [7]:
thearray = np.array([1, 2, 3, 4, 5, 6, 7, 8])
thearray.resize(4)
print(thearray)
 
print("-" * 20)

thearray = np.array([1, 2, 3, 4, 5, 6, 7, 8])
thearray.resize(2, 4)
print(thearray)
 
print("-" * 20)

thearray = np.array([1, 2, 3, 4, 5, 6, 7, 8])
thearray.resize(3, 3)
print(thearray)

[1 2 3 4]
--------------------
[[1 2 3 4]
 [5 6 7 8]]
--------------------
[[1 2 3]
 [4 5 6]
 [7 8 0]]


### Using Numpy function

### - **` Some Built-in Methods for creating arrays `**
***
<font color = #318CE7 size = 3 >
    
- `arange` 

- `linspace`

- `random.rand`
 
</font>

***

In [42]:
# arange
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [46]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [47]:
a_3d = np_a.reshape(3,3)

In [48]:
a_3d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [49]:
np_a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
# Standard Normal Distribution Random Number Generator
snormal = np.random.randn(10000)
print(snormal)
print("mean : ", np.mean(snormal))
print("std. dev.:", np.std(snormal))

[ 1.0756868   2.38130084 -0.22354102 ... -0.36772106  1.25560384
  0.35312165]
mean :  -0.001405520941038791
std. dev.: 1.0025765626720895


## Array Indexing
### - **`Indexing a 2D array (matrices)`**
***
<font color = #318CE7 size = 3 >
    
The general format is `arr_2d[row][col]` or `arr_2d[row,col]`. I recommend usually using the comma notation for clarity.
 
</font>

***

In [52]:
np_a[1]

2

In [60]:
a_3d[1][1]

5

### - **`Conditional Selection`**
***


In [10]:
conarr = np.arange(1,11)
conarr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
conarr > 4 

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [12]:
bool_conarr = conarr > 4
bool_conarr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [13]:
conarr[bool_conarr]

array([ 5,  6,  7,  8,  9, 10])

In [14]:
conarr [ conarr > 2 ] = 100
conarr

array([  1,   2, 100, 100, 100, 100, 100, 100, 100, 100])

## Array Data types

In [66]:
a = np.array([1,2,3,4,5], dtype = np.uint8)

In [67]:
a.dtype

dtype('uint8')

## Array broadcasting

In [73]:
a = np.array([[1.0, 2.0, 3.0],
            [4.0, 5.0, 6.0],
            [7.0, 8.0, 9.0]])

In [77]:
 b = 2*a

In [78]:
a,b

(array([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]]),
 array([[ 2.,  4.,  6.],
        [ 8., 10., 12.],
        [14., 16., 18.]]))

In [79]:
a+b

array([[ 3.,  6.,  9.],
       [12., 15., 18.],
       [21., 24., 27.]])